<?php

namespace Database\Seeders;

use App\Models\Restaurant;
use App\Models\User;
use Illuminate\Database\Seeder;

class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        Restaurant::query()->forceDelete();

        $operatingHoursRegular = $this->operatingHours([
            'Monday' => [['open' => '11:00', 'close' => '22:00']],
            'Tuesday' => [['open' => '11:00', 'close' => '22:00']],
            'Wednesday' => [['open' => '11:00', 'close' => '22:00']],
            'Thursday' => [['open' => '11:00', 'close' => '22:00']],
            'Friday' => [['open' => '11:00', 'close' => '23:00']],
            'Saturday' => [['open' => '10:00', 'close' => '23:00']],
            'Sunday' => [['open' => '10:00', 'close' => '21:00']],
        ]);

        $operatingHoursSplit = $this->operatingHours([
            'Monday' => [['open' => '11:30', 'close' => '14:30'], ['open' => '17:00', 'close' => '22:00']],
            'Tuesday' => [['open' => '11:30', 'close' => '14:30'], ['open' => '17:00', 'close' => '22:00']],
            'Wednesday' => [],
            'Thursday' => [['open' => '11:30', 'close' => '14:30'], ['open' => '17:00', 'close' => '22:00']],
            'Friday' => [['open' => '11:30', 'close' => '14:30'], ['open' => '17:00', 'close' => '23:00']],
            'Saturday' => [['open' => '12:00', 'close' => '15:00'], ['open' => '17:00', 'close' => '23:00']],
            'Sunday' => [['open' => '12:00', 'close' => '21:00']],
        ]);

        $restaurants = [
            [
                'id' => 1,
                'owner_email' => 'restaurant@example.com',
                'restaurant_name' => 'Sushi Masaru',
                'description' => 'Premium omakase and sushi experience in the heart of Ginza. Fresh fish is prepared daily for international guests.',
                'postal_code' => '1040061',
                'prefecture' => 'Tokyo',
                'city' => 'Chuo City',
                'street_address_building' => 'Ginza 4-2-8, 3F',
                'phone_number' => '0312345678',
                'website' => 'https://example.com/sushi-masaru',
                'instagram' => 'sushi_masaru',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 28,
                'stay_duration' => 120,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.671901,
                'longitude' => 139.765,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 2,
                'owner_email' => 'restaurant2@example.com',
                'restaurant_name' => 'Ramen Ichiban',
                'description' => 'Authentic tonkotsu ramen with rich broth and English-friendly service.',
                'postal_code' => '1500043',
                'prefecture' => 'Tokyo',
                'city' => 'Shibuya City',
                'street_address_building' => 'Dogenzaka 1-2-3, 1F',
                'phone_number' => '0398765432',
                'website' => 'https://example.com/ramen-ichiban',
                'instagram' => 'ramen_ichiban',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 36,
                'stay_duration' => 90,
                'operating_hours' => $operatingHoursSplit,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.658034,
                'longitude' => 139.701636,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 3,
                'owner_email' => 'pending-restaurant@example.com',
                'restaurant_name' => 'Yakitori Tori',
                'description' => 'Charcoal-grilled yakitori restaurant waiting for admin approval.',
                'postal_code' => '1600022',
                'prefecture' => 'Tokyo',
                'city' => 'Shinjuku City',
                'street_address_building' => 'Shinjuku 3-17-21, 2F',
                'phone_number' => '0387654321',
                'website' => 'https://example.com/yakitori-tori',
                'instagram' => 'yakitori_tori',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 24,
                'stay_duration' => 120,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.690921,
                'longitude' => 139.700258,
                'status' => Restaurant::STATUS_PENDING,
            ],
            [
                'id' => 4,
                'owner_email' => 'rejected-restaurant@example.com',
                'restaurant_name' => 'Osaka Grill House',
                'description' => 'Rejected sample restaurant for admin status testing.',
                'postal_code' => '5300001',
                'prefecture' => 'Osaka',
                'city' => 'Kita Ward',
                'street_address_building' => 'Umeda 3-2-123, 4F',
                'phone_number' => '0611111111',
                'website' => 'https://example.com/osaka-grill-house',
                'instagram' => null,
                'facebook' => null,
                'twitter' => null,
                'capacity' => 40,
                'stay_duration' => 120,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 34.702485,
                'longitude' => 135.495951,
                'status' => Restaurant::STATUS_REJECTED,
            ],
            [
                'id' => 5,
                'owner_email' => 'suspended-restaurant@example.com',
                'restaurant_name' => 'Sakura Dessert Cafe',
                'description' => 'Suspended sample restaurant for admin status testing.',
                'postal_code' => '7600031',
                'prefecture' => 'Kagawa',
                'city' => 'Takamatsu',
                'street_address_building' => 'Kitahamacho 15-11',
                'phone_number' => '0871010101',
                'website' => 'https://example.com/sakura-dessert-cafe',
                'instagram' => 'sakura_dessert_cafe',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 18,
                'stay_duration' => 90,
                'operating_hours' => $operatingHoursSplit,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 34.342787,
                'longitude' => 134.046574,
                'status' => Restaurant::STATUS_SUSPENDED,
            ],
            [
                'id' => 6,
                'owner_email' => 'restaurant6@example.com',
                'restaurant_name' => 'Tempura Aoi',
                'description' => 'Crisp seasonal tempura served in a calm Asakusa dining room.',
                'postal_code' => '1110032',
                'prefecture' => 'Tokyo',
                'city' => 'Taito City',
                'street_address_building' => 'Asakusa 1-18-7, 2F',
                'phone_number' => '0355551006',
                'website' => 'https://example.com/tempura-aoi',
                'instagram' => 'tempura_aoi',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 26,
                'stay_duration' => 120,
                'operating_hours' => $operatingHoursSplit,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.711856,
                'longitude' => 139.79683,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 7,
                'owner_email' => 'restaurant7@example.com',
                'restaurant_name' => 'Udon Kanda',
                'description' => 'Handmade sanuki-style udon near Kanda Station.',
                'postal_code' => '1010044',
                'prefecture' => 'Tokyo',
                'city' => 'Chiyoda City',
                'street_address_building' => 'Kajicho 2-6-4, 1F',
                'phone_number' => '0355551007',
                'website' => 'https://example.com/udon-kanda',
                'instagram' => 'udon_kanda',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 32,
                'stay_duration' => 75,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.691693,
                'longitude' => 139.770883,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 8,
                'owner_email' => 'restaurant8@example.com',
                'restaurant_name' => 'Green Table Ebisu',
                'description' => 'Plant-based Japanese dishes with vegan and gluten-conscious options.',
                'postal_code' => '1500013',
                'prefecture' => 'Tokyo',
                'city' => 'Shibuya City',
                'street_address_building' => 'Ebisu 1-9-5, 3F',
                'phone_number' => '0355551008',
                'website' => 'https://example.com/green-table-ebisu',
                'instagram' => 'green_table_ebisu',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 30,
                'stay_duration' => 90,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.64669,
                'longitude' => 139.710106,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 9,
                'owner_email' => 'restaurant9@example.com',
                'restaurant_name' => 'Izakaya Lantern',
                'description' => 'Friendly Shinjuku izakaya with small plates and private seating.',
                'postal_code' => '1600023',
                'prefecture' => 'Tokyo',
                'city' => 'Shinjuku City',
                'street_address_building' => 'Nishishinjuku 7-8-10, B1F',
                'phone_number' => '0355551009',
                'website' => 'https://example.com/izakaya-lantern',
                'instagram' => 'izakaya_lantern',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 42,
                'stay_duration' => 120,
                'operating_hours' => $operatingHoursSplit,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.69512,
                'longitude' => 139.69843,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 10,
                'owner_email' => 'restaurant10@example.com',
                'restaurant_name' => 'Tokyo Spice Curry',
                'description' => 'Modern Japanese curry with customizable spice levels.',
                'postal_code' => '1550031',
                'prefecture' => 'Tokyo',
                'city' => 'Setagaya City',
                'street_address_building' => 'Kitazawa 2-14-3, 1F',
                'phone_number' => '0355551010',
                'website' => 'https://example.com/tokyo-spice-curry',
                'instagram' => 'tokyo_spice_curry',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 24,
                'stay_duration' => 75,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.66162,
                'longitude' => 139.66818,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 11,
                'owner_email' => 'restaurant11@example.com',
                'restaurant_name' => 'Trattoria Luna',
                'description' => 'Casual Italian dining with handmade pasta in Daikanyama.',
                'postal_code' => '1500034',
                'prefecture' => 'Tokyo',
                'city' => 'Shibuya City',
                'street_address_building' => 'Daikanyamacho 12-4, 2F',
                'phone_number' => '0355551011',
                'website' => 'https://example.com/trattoria-luna',
                'instagram' => 'trattoria_luna',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 38,
                'stay_duration' => 120,
                'operating_hours' => $operatingHoursSplit,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.64852,
                'longitude' => 139.70321,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 12,
                'owner_email' => 'restaurant12@example.com',
                'restaurant_name' => 'Yakiniku Kaito',
                'description' => 'Japanese barbecue with English menus and table-side grills.',
                'postal_code' => '1060032',
                'prefecture' => 'Tokyo',
                'city' => 'Minato City',
                'street_address_building' => 'Roppongi 5-3-2, 4F',
                'phone_number' => '0355551012',
                'website' => 'https://example.com/yakiniku-kaito',
                'instagram' => 'yakiniku_kaito',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 48,
                'stay_duration' => 120,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.66281,
                'longitude' => 139.73125,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 13,
                'owner_email' => 'restaurant13@example.com',
                'restaurant_name' => 'Siam Garden Tokyo',
                'description' => 'Thai classics and vegetarian options in Ikebukuro.',
                'postal_code' => '1710021',
                'prefecture' => 'Tokyo',
                'city' => 'Toshima City',
                'street_address_building' => 'Nishiikebukuro 1-12-6, 3F',
                'phone_number' => '0355551013',
                'website' => 'https://example.com/siam-garden-tokyo',
                'instagram' => 'siam_garden_tokyo',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 34,
                'stay_duration' => 90,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.72982,
                'longitude' => 139.71082,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 14,
                'owner_email' => 'restaurant14@example.com',
                'restaurant_name' => 'Bistro Marais',
                'description' => 'French-inspired bistro dishes in Kagurazaka.',
                'postal_code' => '1620825',
                'prefecture' => 'Tokyo',
                'city' => 'Shinjuku City',
                'street_address_building' => 'Kagurazaka 4-8, 2F',
                'phone_number' => '0355551014',
                'website' => 'https://example.com/bistro-marais',
                'instagram' => 'bistro_marais',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 28,
                'stay_duration' => 120,
                'operating_hours' => $operatingHoursSplit,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.70198,
                'longitude' => 139.74039,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 15,
                'owner_email' => 'restaurant15@example.com',
                'restaurant_name' => 'Morning Bakery Yanaka',
                'description' => 'Bakery cafe serving fresh bread, sandwiches, and coffee.',
                'postal_code' => '1100001',
                'prefecture' => 'Tokyo',
                'city' => 'Taito City',
                'street_address_building' => 'Yanaka 3-10-8, 1F',
                'phone_number' => '0355551015',
                'website' => 'https://example.com/morning-bakery-yanaka',
                'instagram' => 'morning_bakery_yanaka',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 22,
                'stay_duration' => 75,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.72688,
                'longitude' => 139.76626,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 16,
                'owner_email' => 'restaurant16@example.com',
                'restaurant_name' => 'Sushi Hikari Ginza',
                'description' => 'A modern sushi counter serving seasonal nigiri and approachable omakase courses in Ginza.',
                'postal_code' => '1040061',
                'prefecture' => 'Tokyo',
                'city' => 'Chuo City',
                'street_address_building' => 'Ginza 6-7-4, 2F',
                'phone_number' => '0355551016',
                'website' => 'https://example.com/sushi-hikari-ginza',
                'instagram' => 'sushi_hikari_ginza',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 24,
                'stay_duration' => 120,
                'operating_hours' => $operatingHoursSplit,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.6696,
                'longitude' => 139.7636,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 17,
                'owner_email' => 'restaurant17@example.com',
                'restaurant_name' => 'Asakusa Sushi Sora',
                'description' => 'Casual Edomae sushi near Sensoji with English menus and family-friendly table seating.',
                'postal_code' => '1110032',
                'prefecture' => 'Tokyo',
                'city' => 'Taito City',
                'street_address_building' => 'Asakusa 2-5-9, 1F',
                'phone_number' => '0355551017',
                'website' => 'https://example.com/asakusa-sushi-sora',
                'instagram' => 'asakusa_sushi_sora',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 30,
                'stay_duration' => 105,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.7134,
                'longitude' => 139.7957,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 18,
                'owner_email' => 'restaurant18@example.com',
                'restaurant_name' => 'Ramen Kuro Roppongi',
                'description' => 'Late-night black garlic ramen and crispy gyoza in central Roppongi.',
                'postal_code' => '1060032',
                'prefecture' => 'Tokyo',
                'city' => 'Minato City',
                'street_address_building' => 'Roppongi 4-9-6, 1F',
                'phone_number' => '0355551018',
                'website' => 'https://example.com/ramen-kuro-roppongi',
                'instagram' => 'ramen_kuro_roppongi',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 28,
                'stay_duration' => 75,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.6638,
                'longitude' => 139.7314,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 19,
                'owner_email' => 'restaurant19@example.com',
                'restaurant_name' => 'Ramen Haru Shinjuku',
                'description' => 'Bright chicken paitan ramen, vegetarian broth options, and fast service near Shinjuku Station.',
                'postal_code' => '1600022',
                'prefecture' => 'Tokyo',
                'city' => 'Shinjuku City',
                'street_address_building' => 'Shinjuku 3-28-2, B1F',
                'phone_number' => '0355551019',
                'website' => 'https://example.com/ramen-haru-shinjuku',
                'instagram' => 'ramen_haru_shinjuku',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 34,
                'stay_duration' => 75,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.6902,
                'longitude' => 139.7022,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 20,
                'owner_email' => 'restaurant20@example.com',
                'restaurant_name' => 'Kaiseki Kiyomi',
                'description' => 'Seasonal Japanese kaiseki courses combining tempura, sashimi, grilled wagyu, and matcha dessert.',
                'postal_code' => '1040061',
                'prefecture' => 'Tokyo',
                'city' => 'Chuo City',
                'street_address_building' => 'Ginza 5-11-3, 5F',
                'phone_number' => '0355551020',
                'website' => 'https://example.com/kaiseki-kiyomi',
                'instagram' => 'kaiseki_kiyomi',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 32,
                'stay_duration' => 120,
                'operating_hours' => $operatingHoursSplit,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.6707,
                'longitude' => 139.7659,
                'status' => Restaurant::STATUS_APPROVED,
            ],
            [
                'id' => 21,
                'owner_email' => 'restaurant21@example.com',
                'restaurant_name' => 'Yakitori En Roppongi',
                'description' => 'Charcoal-grilled chicken skewers, local craft beer, and relaxed counter seating.',
                'postal_code' => '1060032',
                'prefecture' => 'Tokyo',
                'city' => 'Minato City',
                'street_address_building' => 'Roppongi 7-8-5, 2F',
                'phone_number' => '0355551021',
                'website' => 'https://example.com/yakitori-en-roppongi',
                'instagram' => 'yakitori_en_roppongi',
                'facebook' => null,
                'twitter' => null,
                'capacity' => 36,
                'stay_duration' => 105,
                'operating_hours' => $operatingHoursRegular,
                'business_license' => 'business_licenses/sample-license.pdf',
                'latitude' => 35.6654,
                'longitude' => 139.7301,
                'status' => Restaurant::STATUS_APPROVED,
            ],
        ];

        foreach ($restaurants as $restaurant) {
            $owner = User::where('email', $restaurant['owner_email'])->firstOrFail();
            unset($restaurant['owner_email']);

            $restaurant['user_id'] = $owner->id;
            $restaurant['created_at'] = now();
            $restaurant['updated_at'] = now();

            Restaurant::withoutEvents(function () use ($restaurant) {
                Restaurant::create($restaurant);
            });
        }
    }

    private function operatingHours(array $days): array
    {
        $weekDays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
        $hours = [];

        foreach ($weekDays as $day) {
            $shifts = $days[$day] ?? [];
            $hours[$day] = ['closed' => empty($shifts)];

            foreach ($shifts as $index => $shift) {
                $hours[$day][$index] = $shift;
            }
        }

        return $hours;
    }
}
